name: Prickly-CD

on:
  push:
    branches:
      -main
permissions: 
  id-token: write
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: aws:iam::753674274065:role/cicd-pipeline
          aws-region: ap-southeast-1
    
      
        
        
      
      
